// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeInfo.proto

package com.bht.pim.proto.employees;

public interface EmployeeIdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.employees.EmployeeId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
