// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectList.proto

package com.bht.pim.proto.project;

public final class ProjectListOuterClass {
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_bht_pim_proto_project_ProjectList_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_bht_pim_proto_project_ProjectList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_bht_pim_proto_project_NoParam_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_bht_pim_proto_project_NoParam_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    String[] descriptorData = {
            "\n\021ProjectList.proto\022\031com.bht.pim.proto.p" +
                    "roject\032\rProject.proto\032\024ProjectNumbers.pr" +
                    "oto\"F\n\013ProjectList\0227\n\013projectList\030\001 \003(\0132" +
                    "\".com.bht.pim.proto.project.Project\"\t\n\007N" +
                    "oParam2\326\001\n\022ProjectListService\022\\\n\016getProj" +
                    "ectList\022\".com.bht.pim.proto.project.NoPa" +
                    "ram\032&.com.bht.pim.proto.project.ProjectL" +
                    "ist\022b\n\021getProjectNumbers\022\".com.bht.pim.p" +
                    "roto.project.NoParam\032).com.bht.pim.proto" +
                    ".project.ProjectNumbersB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                            ProjectOuterClass.getDescriptor(),
                            com.bht.pim.proto.project.ProjectNumbersOuterClass.getDescriptor(),
                    }, assigner);
    internal_static_com_bht_pim_proto_project_ProjectList_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_bht_pim_proto_project_ProjectList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_bht_pim_proto_project_ProjectList_descriptor,
            new String[]{"ProjectList",});
    internal_static_com_bht_pim_proto_project_NoParam_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_com_bht_pim_proto_project_NoParam_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_bht_pim_proto_project_NoParam_descriptor,
            new String[]{});
    ProjectOuterClass.getDescriptor();
    com.bht.pim.proto.project.ProjectNumbersOuterClass.getDescriptor();
  }

  private ProjectListOuterClass() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
