// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info/GroupInfo.proto

package com.bht.pim.proto.groups;

import com.bht.pim.proto.employees.EmployeeInfoOuterClass;

public final class GroupInfoOuterClass {
    private GroupInfoOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_groups_GroupInfo_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_groups_GroupInfo_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\024info/GroupInfo.proto\022\030com.bht.pim.prot" +
                        "o.groups\032\027info/EmployeeInfo.proto\"R\n\tGro" +
                        "upInfo\022\n\n\002id\030\001 \001(\003\0229\n\006leader\030\002 \001(\0132).com" +
                        ".bht.pim.proto.employees.EmployeeInfoB\005P" +
                        "\001\210\001\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    @Override
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                EmployeeInfoOuterClass.getDescriptor(),
                        }, assigner);
        internal_static_com_bht_pim_proto_groups_GroupInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_bht_pim_proto_groups_GroupInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_groups_GroupInfo_descriptor,
                new String[]{"Id", "Leader",});
        EmployeeInfoOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
