// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package com.bht.pim.proto;

public final class Dto {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_Date_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_Date_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_Employee_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_Employee_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_Group_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_Group_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_Project_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_Project_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tdto.proto\022\021com.bht.pim.proto\",\n\004Date\022\n" +
                        "\n\002dd\030\001 \001(\005\022\n\n\002mm\030\002 \001(\005\022\014\n\004yyyy\030\003 \001(\005\"\254\001\n" +
                        "\010Employee\022\n\n\002id\030\001 \001(\003\022\014\n\004visa\030\002 \001(\t\022\022\n\nf" +
                        "irst_name\030\003 \001(\t\022\021\n\tlast_name\030\004 \001(\t\022)\n\010bi" +
                        "rthday\030\005 \001(\0132\027.com.bht.pim.proto.Date\0224\n" +
                        "\020enrolledProjects\030\006 \003(\0132\032.com.bht.pim.pr" +
                        "oto.Project\"\212\001\n\005Group\022\n\n\002id\030\001 \001(\003\022\025\n\rgro" +
                        "upLeaderId\030\002 \001(\003\022\027\n\017groupLeaderVisa\030\003 \001(" +
                        "\t\022\027\n\017groupLeaderName\030\004 \001(\t\022,\n\010projects\030\005" +
                        " \003(\0132\032.com.bht.pim.proto.Project\"\372\001\n\007Pro" +
                        "ject\022\n\n\002id\030\001 \001(\003\022\016\n\006number\030\002 \001(\003\022\'\n\005grou" +
                        "p\030\003 \001(\0132\030.com.bht.pim.proto.Group\022\014\n\004nam" +
                        "e\030\004 \001(\t\022\020\n\010customer\030\005 \001(\t\022\016\n\006status\030\006 \001(" +
                        "\t\022&\n\005start\030\007 \001(\0132\027.com.bht.pim.proto.Dat" +
                        "e\022$\n\003end\030\010 \001(\0132\027.com.bht.pim.proto.Date\022" +
                        ",\n\007members\030\t \003(\0132\033.com.bht.pim.proto.Emp" +
                        "loyeeB\002P\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_bht_pim_proto_Date_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_bht_pim_proto_Date_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_Date_descriptor,
                new java.lang.String[]{"Dd", "Mm", "Yyyy",});
        internal_static_com_bht_pim_proto_Employee_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_bht_pim_proto_Employee_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_Employee_descriptor,
                new java.lang.String[]{"Id", "Visa", "FirstName", "LastName", "Birthday", "EnrolledProjects",});
        internal_static_com_bht_pim_proto_Group_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_com_bht_pim_proto_Group_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_Group_descriptor,
                new java.lang.String[]{"Id", "GroupLeaderId", "GroupLeaderVisa", "GroupLeaderName", "Projects",});
        internal_static_com_bht_pim_proto_Project_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_com_bht_pim_proto_Project_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_Project_descriptor,
                new java.lang.String[]{"Id", "Number", "Group", "Name", "Customer", "Status", "Start", "End", "Members",});
    }

    private Dto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
