// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package com.bht.pim.proto;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string visa = 2;</code>
   */
  java.lang.String getVisa();
  /**
   * <code>string visa = 2;</code>
   */
  com.google.protobuf.ByteString
      getVisaBytes();

  /**
   * <code>string first_name = 3;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 4;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>.com.bht.pim.proto.Date birthday = 5;</code>
   */
  boolean hasBirthday();
  /**
   * <code>.com.bht.pim.proto.Date birthday = 5;</code>
   */
  com.bht.pim.proto.Date getBirthday();
  /**
   * <code>.com.bht.pim.proto.Date birthday = 5;</code>
   */
  com.bht.pim.proto.DateOrBuilder getBirthdayOrBuilder();

  /**
   * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
   */
  java.util.List<com.bht.pim.proto.Project> 
      getEnrolledProjectsList();
  /**
   * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
   */
  com.bht.pim.proto.Project getEnrolledProjects(int index);
  /**
   * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
   */
  int getEnrolledProjectsCount();
  /**
   * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
   */
  java.util.List<? extends com.bht.pim.proto.ProjectOrBuilder> 
      getEnrolledProjectsOrBuilderList();
  /**
   * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
   */
  com.bht.pim.proto.ProjectOrBuilder getEnrolledProjectsOrBuilder(
      int index);
}
