// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package com.bht.pim.proto;

/**
 * Protobuf type {@code com.bht.pim.proto.Employee}
 */
public final class Employee extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bht.pim.proto.Employee)
        EmployeeOrBuilder {
    public static final int ID_FIELD_NUMBER = 1;
    public static final int VISA_FIELD_NUMBER = 2;
    public static final int FIRST_NAME_FIELD_NUMBER = 3;
    public static final int LAST_NAME_FIELD_NUMBER = 4;
    public static final int BIRTHDAY_FIELD_NUMBER = 5;
    public static final int ENROLLEDPROJECTS_FIELD_NUMBER = 6;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.bht.pim.proto.Employee)
    private static final com.bht.pim.proto.Employee DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Employee>
            PARSER = new com.google.protobuf.AbstractParser<Employee>() {
        @java.lang.Override
        public Employee parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Employee(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.bht.pim.proto.Employee();
    }

    private long id_;
    private volatile java.lang.Object visa_;
    private volatile java.lang.Object firstName_;
    private volatile java.lang.Object lastName_;
    private com.bht.pim.proto.Date birthday_;
    private java.util.List<com.bht.pim.proto.Project> enrolledProjects_;
    private byte memoizedIsInitialized = -1;

    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Employee() {
        visa_ = "";
        firstName_ = "";
        lastName_ = "";
        enrolledProjects_ = java.util.Collections.emptyList();
    }

    private Employee(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 8: {

                        id_ = input.readInt64();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        visa_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        firstName_ = s;
                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        lastName_ = s;
                        break;
                    }
                    case 42: {
                        com.bht.pim.proto.Date.Builder subBuilder = null;
                        if (birthday_ != null) {
                            subBuilder = birthday_.toBuilder();
                        }
                        birthday_ = input.readMessage(com.bht.pim.proto.Date.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(birthday_);
                            birthday_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 50: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            enrolledProjects_ = new java.util.ArrayList<>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        enrolledProjects_.add(
                                input.readMessage(com.bht.pim.proto.Project.parser(), extensionRegistry));
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                enrolledProjects_ = java.util.Collections.unmodifiableList(enrolledProjects_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.bht.pim.proto.Dto.internal_static_com_bht_pim_proto_Employee_descriptor;
    }

    public static com.bht.pim.proto.Employee parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.bht.pim.proto.Employee parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.bht.pim.proto.Employee parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.bht.pim.proto.Employee parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.bht.pim.proto.Employee parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.bht.pim.proto.Employee parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.bht.pim.proto.Employee parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.bht.pim.proto.Employee parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bht.pim.proto.Employee parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bht.pim.proto.Employee parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bht.pim.proto.Employee parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.bht.pim.proto.Employee parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.bht.pim.proto.Employee prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.bht.pim.proto.Employee getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Employee> parser() {
        return PARSER;
    }

    @java.lang.Override
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.bht.pim.proto.Dto.internal_static_com_bht_pim_proto_Employee_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.bht.pim.proto.Employee.class, com.bht.pim.proto.Employee.Builder.class);
    }

    /**
     * <code>int64 id = 1;</code>
     */
    @Override
    public long getId() {
        return id_;
    }

    /**
     * <code>string visa = 2;</code>
     */
    @Override
    public java.lang.String getVisa() {
        java.lang.Object ref = visa_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            visa_ = s;
            return s;
        }
    }

    /**
     * <code>string visa = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getVisaBytes() {
        java.lang.Object ref = visa_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            visa_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string first_name = 3;</code>
     */
    @Override
    public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            firstName_ = s;
            return s;
        }
    }

    /**
     * <code>string first_name = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            firstName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string last_name = 4;</code>
     */
    @Override
    public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            lastName_ = s;
            return s;
        }
    }

    /**
     * <code>string last_name = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            lastName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>.com.bht.pim.proto.Date birthday = 5;</code>
     */
    @Override
    public boolean hasBirthday() {
        return birthday_ != null;
    }

    /**
     * <code>.com.bht.pim.proto.Date birthday = 5;</code>
     */
    @Override
    public com.bht.pim.proto.Date getBirthday() {
        return birthday_ == null ? com.bht.pim.proto.Date.getDefaultInstance() : birthday_;
    }

    /**
     * <code>.com.bht.pim.proto.Date birthday = 5;</code>
     */
    @Override
    public com.bht.pim.proto.DateOrBuilder getBirthdayOrBuilder() {
        return getBirthday();
    }

    /**
     * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
     */
    @Override
    public java.util.List<com.bht.pim.proto.Project> getEnrolledProjectsList() {
        return enrolledProjects_;
    }

    /**
     * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
     */
    @Override
    public java.util.List<? extends com.bht.pim.proto.ProjectOrBuilder>
    getEnrolledProjectsOrBuilderList() {
        return enrolledProjects_;
    }

    /**
     * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
     */
    @Override
    public int getEnrolledProjectsCount() {
        return enrolledProjects_.size();
    }

    /**
     * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
     */
    @Override
    public com.bht.pim.proto.Project getEnrolledProjects(int index) {
        return enrolledProjects_.get(index);
    }

    /**
     * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
     */
    @Override
    public com.bht.pim.proto.ProjectOrBuilder getEnrolledProjectsOrBuilder(
            int index) {
        return enrolledProjects_.get(index);
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (id_ != 0L) {
            output.writeInt64(1, id_);
        }
        if (!getVisaBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, visa_);
        }
        if (!getFirstNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, firstName_);
        }
        if (!getLastNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastName_);
        }
        if (birthday_ != null) {
            output.writeMessage(5, getBirthday());
        }
        for (int i = 0; i < enrolledProjects_.size(); i++) {
            output.writeMessage(6, enrolledProjects_.get(i));
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (id_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, id_);
        }
        if (!getVisaBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, visa_);
        }
        if (!getFirstNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, firstName_);
        }
        if (!getLastNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastName_);
        }
        if (birthday_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, getBirthday());
        }
        for (int i = 0; i < enrolledProjects_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(6, enrolledProjects_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.bht.pim.proto.Employee)) {
            return super.equals(obj);
        }
        com.bht.pim.proto.Employee other = (com.bht.pim.proto.Employee) obj;

        if (getId()
                != other.getId()) {
            return false;
        }
        if (!getVisa()
                .equals(other.getVisa())) {
            return false;
        }
        if (!getFirstName()
                .equals(other.getFirstName())) {
            return false;
        }
        if (!getLastName()
                .equals(other.getLastName())) {
            return false;
        }
        if (hasBirthday() != other.hasBirthday()) {
            return false;
        }
        if (hasBirthday()) {
            if (!getBirthday()
                    .equals(other.getBirthday())) {
                return false;
            }
        }
        if (!getEnrolledProjectsList()
                .equals(other.getEnrolledProjectsList())) {
            return false;
        }
        if (!unknownFields.equals(other.unknownFields)) {
            return false;
        }
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getId());
        hash = (37 * hash) + VISA_FIELD_NUMBER;
        hash = (53 * hash) + getVisa().hashCode();
        hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
        hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastName().hashCode();
        if (hasBirthday()) {
            hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
            hash = (53 * hash) + getBirthday().hashCode();
        }
        if (getEnrolledProjectsCount() > 0) {
            hash = (37 * hash) + ENROLLEDPROJECTS_FIELD_NUMBER;
            hash = (53 * hash) + getEnrolledProjectsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.bht.pim.proto.Employee getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.bht.pim.proto.Employee}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.bht.pim.proto.Employee)
            com.bht.pim.proto.EmployeeOrBuilder {
        private int bitField0_;
        private long id_;
        private java.lang.Object visa_ = "";
        private java.lang.Object firstName_ = "";
        private java.lang.Object lastName_ = "";
        private com.bht.pim.proto.Date birthday_;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.bht.pim.proto.Date, com.bht.pim.proto.Date.Builder, com.bht.pim.proto.DateOrBuilder> birthdayBuilder_;
        private java.util.List<com.bht.pim.proto.Project> enrolledProjects_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.bht.pim.proto.Project, com.bht.pim.proto.Project.Builder, com.bht.pim.proto.ProjectOrBuilder> enrolledProjectsBuilder_;

        // Construct using com.bht.pim.proto.Employee.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.bht.pim.proto.Dto.internal_static_com_bht_pim_proto_Employee_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.bht.pim.proto.Dto.internal_static_com_bht_pim_proto_Employee_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.bht.pim.proto.Employee.class, com.bht.pim.proto.Employee.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getEnrolledProjectsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            id_ = 0L;

            visa_ = "";

            firstName_ = "";

            lastName_ = "";

            if (birthdayBuilder_ == null) {
                birthday_ = null;
            } else {
                birthday_ = null;
                birthdayBuilder_ = null;
            }
            if (enrolledProjectsBuilder_ == null) {
                enrolledProjects_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                enrolledProjectsBuilder_.clear();
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.bht.pim.proto.Dto.internal_static_com_bht_pim_proto_Employee_descriptor;
        }

        @java.lang.Override
        public com.bht.pim.proto.Employee getDefaultInstanceForType() {
            return com.bht.pim.proto.Employee.getDefaultInstance();
        }

        @java.lang.Override
        public com.bht.pim.proto.Employee build() {
            com.bht.pim.proto.Employee result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.bht.pim.proto.Employee buildPartial() {
            com.bht.pim.proto.Employee result = new com.bht.pim.proto.Employee(this);
            int from_bitField0_ = bitField0_;
            result.id_ = id_;
            result.visa_ = visa_;
            result.firstName_ = firstName_;
            result.lastName_ = lastName_;
            if (birthdayBuilder_ == null) {
                result.birthday_ = birthday_;
            } else {
                result.birthday_ = birthdayBuilder_.build();
            }
            if (enrolledProjectsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    enrolledProjects_ = java.util.Collections.unmodifiableList(enrolledProjects_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.enrolledProjects_ = enrolledProjects_;
            } else {
                result.enrolledProjects_ = enrolledProjectsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.bht.pim.proto.Employee) {
                return mergeFrom((com.bht.pim.proto.Employee) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.bht.pim.proto.Employee other) {
            if (other == com.bht.pim.proto.Employee.getDefaultInstance()) {
                return this;
            }
            if (other.getId() != 0L) {
                setId(other.getId());
            }
            if (!other.getVisa().isEmpty()) {
                visa_ = other.visa_;
                onChanged();
            }
            if (!other.getFirstName().isEmpty()) {
                firstName_ = other.firstName_;
                onChanged();
            }
            if (!other.getLastName().isEmpty()) {
                lastName_ = other.lastName_;
                onChanged();
            }
            if (other.hasBirthday()) {
                mergeBirthday(other.getBirthday());
            }
            if (enrolledProjectsBuilder_ == null) {
                if (!other.enrolledProjects_.isEmpty()) {
                    if (enrolledProjects_.isEmpty()) {
                        enrolledProjects_ = other.enrolledProjects_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureEnrolledProjectsIsMutable();
                        enrolledProjects_.addAll(other.enrolledProjects_);
                    }
                    onChanged();
                }
            } else {
                if (!other.enrolledProjects_.isEmpty()) {
                    if (enrolledProjectsBuilder_.isEmpty()) {
                        enrolledProjectsBuilder_.dispose();
                        enrolledProjectsBuilder_ = null;
                        enrolledProjects_ = other.enrolledProjects_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        enrolledProjectsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getEnrolledProjectsFieldBuilder() : null;
                    } else {
                        enrolledProjectsBuilder_.addAllMessages(other.enrolledProjects_);
                    }
                }
            }
            mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.bht.pim.proto.Employee parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.bht.pim.proto.Employee) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int64 id = 1;</code>
         */
        @Override
        public long getId() {
            return id_;
        }

        /**
         * <code>int64 id = 1;</code>
         */
        public Builder setId(long value) {

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 id = 1;</code>
         */
        public Builder clearId() {

            id_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <code>string visa = 2;</code>
         */
        @Override
        public java.lang.String getVisa() {
            java.lang.Object ref = visa_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                visa_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string visa = 2;</code>
         */
        public Builder setVisa(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            visa_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string visa = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getVisaBytes() {
            java.lang.Object ref = visa_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                visa_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string visa = 2;</code>
         */
        public Builder setVisaBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            visa_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string visa = 2;</code>
         */
        public Builder clearVisa() {

            visa_ = getDefaultInstance().getVisa();
            onChanged();
            return this;
        }

        /**
         * <code>string first_name = 3;</code>
         */
        @Override
        public java.lang.String getFirstName() {
            java.lang.Object ref = firstName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                firstName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public Builder setFirstName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            firstName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string first_name = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getFirstNameBytes() {
            java.lang.Object ref = firstName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                firstName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public Builder setFirstNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            firstName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public Builder clearFirstName() {

            firstName_ = getDefaultInstance().getFirstName();
            onChanged();
            return this;
        }

        /**
         * <code>string last_name = 4;</code>
         */
        @Override
        public java.lang.String getLastName() {
            java.lang.Object ref = lastName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                lastName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public Builder setLastName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            lastName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string last_name = 4;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getLastNameBytes() {
            java.lang.Object ref = lastName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                lastName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public Builder setLastNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            lastName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public Builder clearLastName() {

            lastName_ = getDefaultInstance().getLastName();
            onChanged();
            return this;
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        @Override
        public boolean hasBirthday() {
            return birthdayBuilder_ != null || birthday_ != null;
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        @Override
        public com.bht.pim.proto.Date getBirthday() {
            if (birthdayBuilder_ == null) {
                return birthday_ == null ? com.bht.pim.proto.Date.getDefaultInstance() : birthday_;
            } else {
                return birthdayBuilder_.getMessage();
            }
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        public Builder setBirthday(com.bht.pim.proto.Date value) {
            if (birthdayBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                birthday_ = value;
                onChanged();
            } else {
                birthdayBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        public Builder setBirthday(
                com.bht.pim.proto.Date.Builder builderForValue) {
            if (birthdayBuilder_ == null) {
                birthday_ = builderForValue.build();
                onChanged();
            } else {
                birthdayBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        public Builder mergeBirthday(com.bht.pim.proto.Date value) {
            if (birthdayBuilder_ == null) {
                if (birthday_ != null) {
                    birthday_ =
                            com.bht.pim.proto.Date.newBuilder(birthday_).mergeFrom(value).buildPartial();
                } else {
                    birthday_ = value;
                }
                onChanged();
            } else {
                birthdayBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        public Builder clearBirthday() {
            if (birthdayBuilder_ == null) {
                birthday_ = null;
                onChanged();
            } else {
                birthday_ = null;
                birthdayBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        public com.bht.pim.proto.Date.Builder getBirthdayBuilder() {

            onChanged();
            return getBirthdayFieldBuilder().getBuilder();
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        @Override
        public com.bht.pim.proto.DateOrBuilder getBirthdayOrBuilder() {
            if (birthdayBuilder_ != null) {
                return birthdayBuilder_.getMessageOrBuilder();
            } else {
                return birthday_ == null ?
                        com.bht.pim.proto.Date.getDefaultInstance() : birthday_;
            }
        }

        /**
         * <code>.com.bht.pim.proto.Date birthday = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.bht.pim.proto.Date, com.bht.pim.proto.Date.Builder, com.bht.pim.proto.DateOrBuilder>
        getBirthdayFieldBuilder() {
            if (birthdayBuilder_ == null) {
                birthdayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<>(
                        getBirthday(),
                        getParentForChildren(),
                        isClean());
                birthday_ = null;
            }
            return birthdayBuilder_;
        }

        private void ensureEnrolledProjectsIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                enrolledProjects_ = new java.util.ArrayList<>(enrolledProjects_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        @Override
        public java.util.List<com.bht.pim.proto.Project> getEnrolledProjectsList() {
            if (enrolledProjectsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(enrolledProjects_);
            } else {
                return enrolledProjectsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        @Override
        public int getEnrolledProjectsCount() {
            if (enrolledProjectsBuilder_ == null) {
                return enrolledProjects_.size();
            } else {
                return enrolledProjectsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        @Override
        public com.bht.pim.proto.Project getEnrolledProjects(int index) {
            if (enrolledProjectsBuilder_ == null) {
                return enrolledProjects_.get(index);
            } else {
                return enrolledProjectsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder setEnrolledProjects(
                int index, com.bht.pim.proto.Project value) {
            if (enrolledProjectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.set(index, value);
                onChanged();
            } else {
                enrolledProjectsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder setEnrolledProjects(
                int index, com.bht.pim.proto.Project.Builder builderForValue) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.set(index, builderForValue.build());
                onChanged();
            } else {
                enrolledProjectsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder addEnrolledProjects(com.bht.pim.proto.Project value) {
            if (enrolledProjectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(value);
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder addEnrolledProjects(
                int index, com.bht.pim.proto.Project value) {
            if (enrolledProjectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(index, value);
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder addEnrolledProjects(
                com.bht.pim.proto.Project.Builder builderForValue) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(builderForValue.build());
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder addEnrolledProjects(
                int index, com.bht.pim.proto.Project.Builder builderForValue) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(index, builderForValue.build());
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder addAllEnrolledProjects(
                java.lang.Iterable<? extends com.bht.pim.proto.Project> values) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, enrolledProjects_);
                onChanged();
            } else {
                enrolledProjectsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder clearEnrolledProjects() {
            if (enrolledProjectsBuilder_ == null) {
                enrolledProjects_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                enrolledProjectsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public Builder removeEnrolledProjects(int index) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.remove(index);
                onChanged();
            } else {
                enrolledProjectsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public com.bht.pim.proto.Project.Builder getEnrolledProjectsBuilder(
                int index) {
            return getEnrolledProjectsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        @Override
        public com.bht.pim.proto.ProjectOrBuilder getEnrolledProjectsOrBuilder(
                int index) {
            if (enrolledProjectsBuilder_ == null) {
                return enrolledProjects_.get(index);
            } else {
                return enrolledProjectsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        @Override
        public java.util.List<? extends com.bht.pim.proto.ProjectOrBuilder>
        getEnrolledProjectsOrBuilderList() {
            if (enrolledProjectsBuilder_ != null) {
                return enrolledProjectsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(enrolledProjects_);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public com.bht.pim.proto.Project.Builder addEnrolledProjectsBuilder() {
            return getEnrolledProjectsFieldBuilder().addBuilder(
                    com.bht.pim.proto.Project.getDefaultInstance());
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public com.bht.pim.proto.Project.Builder addEnrolledProjectsBuilder(
                int index) {
            return getEnrolledProjectsFieldBuilder().addBuilder(
                    index, com.bht.pim.proto.Project.getDefaultInstance());
        }

        /**
         * <code>repeated .com.bht.pim.proto.Project enrolledProjects = 6;</code>
         */
        public java.util.List<com.bht.pim.proto.Project.Builder>
        getEnrolledProjectsBuilderList() {
            return getEnrolledProjectsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.bht.pim.proto.Project, com.bht.pim.proto.Project.Builder, com.bht.pim.proto.ProjectOrBuilder>
        getEnrolledProjectsFieldBuilder() {
            if (enrolledProjectsBuilder_ == null) {
                enrolledProjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<>(
                        enrolledProjects_,
                        ((bitField0_ & 0x00000001) != 0),
                        getParentForChildren(),
                        isClean());
                enrolledProjects_ = null;
            }
            return enrolledProjectsBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.bht.pim.proto.Employee)
    }

}

