// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Date.proto

package com.bht.pim.proto.date;

/**
 * Protobuf type {@code com.bht.pim.proto.date.Date}
 */
public final class Date extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bht.pim.proto.date.Date)
        DateOrBuilder {
    public static final int DD_FIELD_NUMBER = 1;
    public static final int MM_FIELD_NUMBER = 2;
    public static final int YYYY_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.bht.pim.proto.date.Date)
    private static final Date DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Date>
            PARSER = new com.google.protobuf.AbstractParser<Date>() {
        public Date parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Date(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new Date();
    }

    private int dd_;
    private int mm_;
    private int yyyy_;
    private byte memoizedIsInitialized = -1;

    // Use Date.newBuilder() to construct.
    private Date(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Date() {
        dd_ = 0;
        mm_ = 0;
        yyyy_ = 0;
    }

    private Date(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        dd_ = input.readInt32();
                        break;
                    }
                    case 16: {

                        mm_ = input.readInt32();
                        break;
                    }
                    case 24: {

                        yyyy_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.bht.pim.proto.date.DateOuterClass.internal_static_com_bht_pim_proto_date_Date_descriptor;
    }

    public static Date parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Date parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Date parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Date parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Date parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Date parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Date parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Date parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Date parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Date parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Date parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Date parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Date prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static Date getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Date> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.bht.pim.proto.date.DateOuterClass.internal_static_com_bht_pim_proto_date_Date_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Date.class, Builder.class);
    }

    /**
     * <code>int32 dd = 1;</code>
     */
    public int getDd() {
        return dd_;
    }

    /**
     * <code>int32 mm = 2;</code>
     */
    public int getMm() {
        return mm_;
    }

    /**
     * <code>int32 yyyy = 3;</code>
     */
    public int getYyyy() {
        return yyyy_;
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (dd_ != 0) {
            output.writeInt32(1, dd_);
        }
        if (mm_ != 0) {
            output.writeInt32(2, mm_);
        }
        if (yyyy_ != 0) {
            output.writeInt32(3, yyyy_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (dd_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, dd_);
        }
        if (mm_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, mm_);
        }
        if (yyyy_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, yyyy_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Date)) {
            return super.equals(obj);
        }
        Date other = (Date) obj;

        boolean result = true;
        result = result && (getDd()
                == other.getDd());
        result = result && (getMm()
                == other.getMm());
        result = result && (getYyyy()
                == other.getYyyy());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DD_FIELD_NUMBER;
        hash = (53 * hash) + getDd();
        hash = (37 * hash) + MM_FIELD_NUMBER;
        hash = (53 * hash) + getMm();
        hash = (37 * hash) + YYYY_FIELD_NUMBER;
        hash = (53 * hash) + getYyyy();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<Date> getParserForType() {
        return PARSER;
    }

    public Date getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.bht.pim.proto.date.Date}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.bht.pim.proto.date.Date)
            com.bht.pim.proto.date.DateOrBuilder {
        private int dd_;
        private int mm_;
        private int yyyy_;

        // Construct using com.bht.pim.proto.date.Date.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.bht.pim.proto.date.DateOuterClass.internal_static_com_bht_pim_proto_date_Date_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.bht.pim.proto.date.DateOuterClass.internal_static_com_bht_pim_proto_date_Date_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Date.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            dd_ = 0;

            mm_ = 0;

            yyyy_ = 0;

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.bht.pim.proto.date.DateOuterClass.internal_static_com_bht_pim_proto_date_Date_descriptor;
        }

        public Date getDefaultInstanceForType() {
            return Date.getDefaultInstance();
        }

        public Date build() {
            Date result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public Date buildPartial() {
            Date result = new Date(this);
            result.dd_ = dd_;
            result.mm_ = mm_;
            result.yyyy_ = yyyy_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Date) {
                return mergeFrom((Date) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Date other) {
            if (other == Date.getDefaultInstance()) return this;
            if (other.getDd() != 0) {
                setDd(other.getDd());
            }
            if (other.getMm() != 0) {
                setMm(other.getMm());
            }
            if (other.getYyyy() != 0) {
                setYyyy(other.getYyyy());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Date parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Date) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int32 dd = 1;</code>
         */
        public int getDd() {
            return dd_;
        }

        /**
         * <code>int32 dd = 1;</code>
         */
        public Builder setDd(int value) {

            dd_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 dd = 1;</code>
         */
        public Builder clearDd() {

            dd_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>int32 mm = 2;</code>
         */
        public int getMm() {
            return mm_;
        }

        /**
         * <code>int32 mm = 2;</code>
         */
        public Builder setMm(int value) {

            mm_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 mm = 2;</code>
         */
        public Builder clearMm() {

            mm_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>int32 yyyy = 3;</code>
         */
        public int getYyyy() {
            return yyyy_;
        }

        /**
         * <code>int32 yyyy = 3;</code>
         */
        public Builder setYyyy(int value) {

            yyyy_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 yyyy = 3;</code>
         */
        public Builder clearYyyy() {

            yyyy_ = 0;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.bht.pim.proto.date.Date)
    }

}

