// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectInfo.proto

package com.bht.pim.proto.projects;

public interface SuccessOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.projects.Success)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();
}
