// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectInfo.proto

package com.bht.pim.proto.projects;

import com.bht.pim.proto.employees.EmployeeOuterClass;
import com.bht.pim.proto.groups.GroupOuterClass;

public final class ProjectInfoOuterClass {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_projects_ProjectInfo_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_projects_ProjectInfo_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\021ProjectInfo.proto\022\032com.bht.pim.proto.p" +
                        "rojects\032\036google/protobuf/wrappers.proto\032" +
                        "\rProject.proto\032\016Employee.proto\032\013Group.pr" +
                        "oto\"}\n\013ProjectInfo\0224\n\007project\030\001 \001(\0132#.co" +
                        "m.bht.pim.proto.projects.Project\0228\n\templ" +
                        "oyees\030\002 \003(\0132%.com.bht.pim.proto.employee" +
                        "s.Employee2\334\002\n\016ProjectService\022V\n\016getProj" +
                        "ectById\022\033.google.protobuf.Int64Value\032\'.c" +
                        "om.bht.pim.proto.projects.ProjectInfo\022T\n" +
                        "\raddNewProject\022\'.com.bht.pim.proto.proje" +
                        "cts.ProjectInfo\032\032.google.protobuf.BoolVa" +
                        "lue\022R\n\013editProject\022\'.com.bht.pim.proto.p" +
                        "rojects.ProjectInfo\032\032.google.protobuf.Bo" +
                        "olValue\022H\n\rdeleteProject\022\033.google.protob" +
                        "uf.Int64Value\032\032.google.protobuf.BoolValu" +
                        "eB\005P\001\210\001\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    @Override
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.WrappersProto.getDescriptor(),
                                ProjectOuterClass.getDescriptor(),
                                EmployeeOuterClass.getDescriptor(),
                                GroupOuterClass.getDescriptor(),
                        }, assigner);
        internal_static_com_bht_pim_proto_projects_ProjectInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_bht_pim_proto_projects_ProjectInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_projects_ProjectInfo_descriptor,
                new String[]{"Project", "Employees",});
        com.google.protobuf.WrappersProto.getDescriptor();
        ProjectOuterClass.getDescriptor();
        EmployeeOuterClass.getDescriptor();
        GroupOuterClass.getDescriptor();
    }

    private ProjectInfoOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
