// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeList.proto

package com.bht.pim.proto.employees;

public final class EmployeeListOuterClass {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_employees_EmployeeList_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_employees_EmployeeList_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\022EmployeeList.proto\022\033com.bht.pim.proto." +
                        "employees\032\033google/protobuf/empty.proto\032\016" +
                        "Employee.proto\"H\n\014EmployeeList\0228\n\temploy" +
                        "ees\030\001 \003(\0132%.com.bht.pim.proto.employees." +
                        "Employee2k\n\023EmployeeListService\022T\n\017getEm" +
                        "ployeeList\022\026.google.protobuf.Empty\032).com" +
                        ".bht.pim.proto.employees.EmployeeListB\005P" +
                        "\001\210\001\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    @Override
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.EmptyProto.getDescriptor(),
                                EmployeeOuterClass.getDescriptor(),
                        }, assigner);
        internal_static_com_bht_pim_proto_employees_EmployeeList_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_bht_pim_proto_employees_EmployeeList_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_employees_EmployeeList_descriptor,
                new String[]{"Employees",});
        com.google.protobuf.EmptyProto.getDescriptor();
        EmployeeOuterClass.getDescriptor();
    }

    private EmployeeListOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
