// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeInfo.proto

package com.bht.pim.proto.employees;

/**
 * Protobuf service {@code com.bht.pim.proto.employees.EmployeeService}
 */
public abstract class EmployeeService
        implements com.google.protobuf.Service {
    protected EmployeeService() {
    }

    public static com.google.protobuf.Service newReflectiveService(
            final Interface impl) {
        return new EmployeeService() {
            @Override
            public void getEmployeeById(
                    com.google.protobuf.RpcController controller,
                    com.google.protobuf.Int64Value request,
                    com.google.protobuf.RpcCallback<EmployeeInfo> done) {
                impl.getEmployeeById(controller, request, done);
            }

        };
    }

    public static com.google.protobuf.BlockingService
    newReflectiveBlockingService(final BlockingInterface impl) {
        return new com.google.protobuf.BlockingService() {
            @Override
            public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            @Override
            public final com.google.protobuf.Message callBlockingMethod(
                    com.google.protobuf.Descriptors.MethodDescriptor method,
                    com.google.protobuf.RpcController controller,
                    com.google.protobuf.Message request)
                    throws com.google.protobuf.ServiceException {
                if (method.getService() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "Service.callBlockingMethod() given method descriptor for " +
                                    "wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return impl.getEmployeeById(controller, (com.google.protobuf.Int64Value) request);
                    default:
                        throw new AssertionError("Can't get here.");
                }
            }

            @Override
            public final com.google.protobuf.Message
            getRequestPrototype(
                    com.google.protobuf.Descriptors.MethodDescriptor method) {
                if (method.getService() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "Service.getRequestPrototype() given method " +
                                    "descriptor for wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return com.google.protobuf.Int64Value.getDefaultInstance();
                    default:
                        throw new AssertionError("Can't get here.");
                }
            }

            @Override
            public final com.google.protobuf.Message
            getResponsePrototype(
                    com.google.protobuf.Descriptors.MethodDescriptor method) {
                if (method.getService() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "Service.getResponsePrototype() given method " +
                                    "descriptor for wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return EmployeeInfo.getDefaultInstance();
                    default:
                        throw new AssertionError("Can't get here.");
                }
            }

        };
    }

    public static final com.google.protobuf.Descriptors.ServiceDescriptor
    getDescriptor() {
        return EmployeeInfoOuterClass.getDescriptor().getServices().get(0);
    }

    public static Stub newStub(
            com.google.protobuf.RpcChannel channel) {
        return new Stub(channel);
    }

    public static BlockingInterface newBlockingStub(
            com.google.protobuf.BlockingRpcChannel channel) {
        return new BlockingStub(channel);
    }

    /**
     * <code>rpc getEmployeeById(.google.protobuf.Int64Value) returns (.com.bht.pim.proto.employees.EmployeeInfo);</code>
     */
    public abstract void getEmployeeById(
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Int64Value request,
            com.google.protobuf.RpcCallback<EmployeeInfo> done);

    @Override
    public final com.google.protobuf.Descriptors.ServiceDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    @Override
    public final void callMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request,
            com.google.protobuf.RpcCallback<
                    com.google.protobuf.Message> done) {
        if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
                    "Service.callMethod() given method descriptor for wrong " +
                            "service type.");
        }
        switch (method.getIndex()) {
            case 0:
                getEmployeeById(controller, (com.google.protobuf.Int64Value) request,
                        com.google.protobuf.RpcUtil.<EmployeeInfo>specializeCallback(
                                done));
                return;
            default:
                throw new AssertionError("Can't get here.");
        }
    }

    @Override
    public final com.google.protobuf.Message
    getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
                    "Service.getRequestPrototype() given method " +
                            "descriptor for wrong service type.");
        }
        switch (method.getIndex()) {
            case 0:
                return com.google.protobuf.Int64Value.getDefaultInstance();
            default:
                throw new AssertionError("Can't get here.");
        }
    }

    @Override
    public final com.google.protobuf.Message
    getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
                    "Service.getResponsePrototype() given method " +
                            "descriptor for wrong service type.");
        }
        switch (method.getIndex()) {
            case 0:
                return EmployeeInfo.getDefaultInstance();
            default:
                throw new AssertionError("Can't get here.");
        }
    }

    public interface Interface {
        /**
         * <code>rpc getEmployeeById(.google.protobuf.Int64Value) returns (.com.bht.pim.proto.employees.EmployeeInfo);</code>
         */
        public abstract void getEmployeeById(
                com.google.protobuf.RpcController controller,
                com.google.protobuf.Int64Value request,
                com.google.protobuf.RpcCallback<EmployeeInfo> done);

    }

    public interface BlockingInterface {
        public EmployeeInfo getEmployeeById(
                com.google.protobuf.RpcController controller,
                com.google.protobuf.Int64Value request)
                throws com.google.protobuf.ServiceException;
    }

    public static final class Stub extends EmployeeService implements Interface {
        private final com.google.protobuf.RpcChannel channel;

        private Stub(com.google.protobuf.RpcChannel channel) {
            this.channel = channel;
        }

        public com.google.protobuf.RpcChannel getChannel() {
            return channel;
        }

        @Override
        public void getEmployeeById(
                com.google.protobuf.RpcController controller,
                com.google.protobuf.Int64Value request,
                com.google.protobuf.RpcCallback<EmployeeInfo> done) {
            channel.callMethod(
                    getDescriptor().getMethods().get(0),
                    controller,
                    request,
                    EmployeeInfo.getDefaultInstance(),
                    com.google.protobuf.RpcUtil.generalizeCallback(
                            done,
                            EmployeeInfo.class,
                            EmployeeInfo.getDefaultInstance()));
        }
    }

    private static final class BlockingStub implements BlockingInterface {
        private final com.google.protobuf.BlockingRpcChannel channel;

        private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
            this.channel = channel;
        }

        @Override
        public EmployeeInfo getEmployeeById(
                com.google.protobuf.RpcController controller,
                com.google.protobuf.Int64Value request)
                throws com.google.protobuf.ServiceException {
            return (EmployeeInfo) channel.callBlockingMethod(
                    getDescriptor().getMethods().get(0),
                    controller,
                    request,
                    EmployeeInfo.getDefaultInstance());
        }

    }

    // @@protoc_insertion_point(class_scope:com.bht.pim.proto.employees.EmployeeService)
}

