// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info/GroupInfo.proto

package com.bht.pim.proto.groups;

import com.bht.pim.proto.employees.EmployeeInfo;
import com.bht.pim.proto.employees.EmployeeInfoOrBuilder;

public interface GroupInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.groups.GroupInfo)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>.com.bht.pim.proto.employees.EmployeeInfo leader = 2;</code>
     */
    boolean hasLeader();

    /**
     * <code>.com.bht.pim.proto.employees.EmployeeInfo leader = 2;</code>
     */
    EmployeeInfo getLeader();

    /**
     * <code>.com.bht.pim.proto.employees.EmployeeInfo leader = 2;</code>
     */
    EmployeeInfoOrBuilder getLeaderOrBuilder();
}
