// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeList.proto

package com.bht.pim.proto.employees;

public interface EmployeeListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.employees.EmployeeList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    java.util.List<Employee>
    getEmployeeList();

    /**
     * <code>repeated .com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    Employee getEmployee(int index);

    /**
     * <code>repeated .com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    int getEmployeeCount();

    /**
     * <code>repeated .com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    java.util.List<? extends EmployeeOrBuilder>
    getEmployeeOrBuilderList();

    /**
     * <code>repeated .com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    EmployeeOrBuilder getEmployeeOrBuilder(
            int index);
}
