// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeInfo.proto

package com.bht.pim.proto.employees;

import com.bht.pim.proto.projects.Project;
import com.bht.pim.proto.projects.ProjectOrBuilder;

public interface EmployeeInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.employees.EmployeeInfo)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    boolean hasEmployee();

    /**
     * <code>.com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    Employee getEmployee();

    /**
     * <code>.com.bht.pim.proto.employees.Employee employee = 1;</code>
     */
    EmployeeOrBuilder getEmployeeOrBuilder();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    java.util.List<Project>
    getEnrolledProjectList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    Project getEnrolledProject(int index);

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    int getEnrolledProjectCount();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    java.util.List<? extends ProjectOrBuilder>
    getEnrolledProjectOrBuilderList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    ProjectOrBuilder getEnrolledProjectOrBuilder(
            int index);
}
