// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeList.proto

package com.bht.pim.proto.employee;

public final class EmployeeListOuterClass {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_employee_EmployeeList_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_employee_EmployeeList_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_bht_pim_proto_employee_NoParam_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_bht_pim_proto_employee_NoParam_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\022EmployeeList.proto\022\032com.bht.pim.proto." +
                        "employee\032\016Employee.proto\"J\n\014EmployeeList" +
                        "\022:\n\014employeeList\030\001 \003(\0132$.com.bht.pim.pro" +
                        "to.employee.Employee\"\t\n\007NoParam2w\n\023Emplo" +
                        "yeeListService\022`\n\017getEmployeeList\022#.com." +
                        "bht.pim.proto.employee.NoParam\032(.com.bht" +
                        ".pim.proto.employee.EmployeeListB\002P\001b\006pr" +
                        "oto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                EmployeeOuterClass.getDescriptor(),
                        }, assigner);
        internal_static_com_bht_pim_proto_employee_EmployeeList_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_bht_pim_proto_employee_EmployeeList_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_employee_EmployeeList_descriptor,
                new String[]{"EmployeeList",});
        internal_static_com_bht_pim_proto_employee_NoParam_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_bht_pim_proto_employee_NoParam_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_bht_pim_proto_employee_NoParam_descriptor,
                new String[]{});
        EmployeeOuterClass.getDescriptor();
    }

    private EmployeeListOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
