// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.bht.pim.proto.employee;

/**
 * Protobuf type {@code com.bht.pim.proto.employee.Employee}
 */
public final class Employee extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bht.pim.proto.employee.Employee)
        EmployeeOrBuilder {
  public static final int ID_FIELD_NUMBER = 1;
  public static final int VISA_FIELD_NUMBER = 2;
  public static final int FIRST_NAME_FIELD_NUMBER = 3;
  public static final int LAST_NAME_FIELD_NUMBER = 4;
  public static final int BIRTHDAY_FIELD_NUMBER = 5;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.bht.pim.proto.employee.Employee)
  private static final Employee DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<Employee>
          PARSER = new com.google.protobuf.AbstractParser<Employee>() {
    public Employee parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new Employee(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new Employee();
  }

  private long id_;
  private volatile Object visa_;
  private volatile Object firstName_;
  private volatile Object lastName_;
  private long birthday_;
  private byte memoizedIsInitialized = -1;

  // Use Employee.newBuilder() to construct.
  private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Employee() {
    id_ = 0L;
    visa_ = "";
    firstName_ = "";
    lastName_ = "";
    birthday_ = 0L;
  }

  private Employee(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            visa_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            firstName_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            lastName_ = s;
            break;
          }
          case 40: {

            birthday_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.bht.pim.proto.employee.EmployeeOuterClass.internal_static_com_bht_pim_proto_employee_Employee_descriptor;
  }

  public static Employee parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static Employee parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static Employee parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static Employee parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static Employee parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static Employee parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static Employee parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static Employee parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Employee parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static Employee parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static Employee parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static Employee parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(Employee prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static Employee getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<Employee> parser() {
    return PARSER;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.bht.pim.proto.employee.EmployeeOuterClass.internal_static_com_bht_pim_proto_employee_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    Employee.class, Builder.class);
  }

  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  /**
   * <code>string visa = 2;</code>
   */
  public String getVisa() {
    Object ref = visa_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      visa_ = s;
      return s;
    }
  }

  /**
   * <code>string visa = 2;</code>
   */
  public com.google.protobuf.ByteString
  getVisaBytes() {
    Object ref = visa_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      visa_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string first_name = 3;</code>
   */
  public String getFirstName() {
    Object ref = firstName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }

  /**
   * <code>string first_name = 3;</code>
   */
  public com.google.protobuf.ByteString
  getFirstNameBytes() {
    Object ref = firstName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string last_name = 4;</code>
   */
  public String getLastName() {
    Object ref = lastName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }

  /**
   * <code>string last_name = 4;</code>
   */
  public com.google.protobuf.ByteString
  getLastNameBytes() {
    Object ref = lastName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>int64 birthday = 5;</code>
   */
  public long getBirthday() {
    return birthday_;
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getVisaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, visa_);
    }
    if (!getFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, firstName_);
    }
    if (!getLastNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastName_);
    }
    if (birthday_ != 0L) {
      output.writeInt64(5, birthday_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(1, id_);
    }
    if (!getVisaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, visa_);
    }
    if (!getFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, firstName_);
    }
    if (!getLastNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastName_);
    }
    if (birthday_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(5, birthday_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof Employee)) {
      return super.equals(obj);
    }
    Employee other = (Employee) obj;

    boolean result = true;
    result = result && (getId()
            == other.getId());
    result = result && getVisa()
            .equals(other.getVisa());
    result = result && getFirstName()
            .equals(other.getFirstName());
    result = result && getLastName()
            .equals(other.getLastName());
    result = result && (getBirthday()
            == other.getBirthday());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
    hash = (37 * hash) + VISA_FIELD_NUMBER;
    hash = (53 * hash) + getVisa().hashCode();
    hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBirthday());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {
    return newBuilder();
  }

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
          BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @Override
  public com.google.protobuf.Parser<Employee> getParserForType() {
    return PARSER;
  }

  public Employee getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.bht.pim.proto.employee.Employee}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.bht.pim.proto.employee.Employee)
          com.bht.pim.proto.employee.EmployeeOrBuilder {
    private long id_;
    private Object visa_ = "";
    private Object firstName_ = "";
    private Object lastName_ = "";
    private long birthday_;

    // Construct using com.bht.pim.proto.employee.Employee.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.bht.pim.proto.employee.EmployeeOuterClass.internal_static_com_bht_pim_proto_employee_Employee_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.bht.pim.proto.employee.EmployeeOuterClass.internal_static_com_bht_pim_proto_employee_Employee_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Employee.class, Builder.class);
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    public Builder clear() {
      super.clear();
      id_ = 0L;

      visa_ = "";

      firstName_ = "";

      lastName_ = "";

      birthday_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.bht.pim.proto.employee.EmployeeOuterClass.internal_static_com_bht_pim_proto_employee_Employee_descriptor;
    }

    public Employee getDefaultInstanceForType() {
      return Employee.getDefaultInstance();
    }

    public Employee build() {
      Employee result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Employee buildPartial() {
      Employee result = new Employee(this);
      result.id_ = id_;
      result.visa_ = visa_;
      result.firstName_ = firstName_;
      result.lastName_ = lastName_;
      result.birthday_ = birthday_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return (Builder) super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Employee) {
        return mergeFrom((Employee) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Employee other) {
      if (other == Employee.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getVisa().isEmpty()) {
        visa_ = other.visa_;
        onChanged();
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (other.getBirthday() != 0L) {
        setBirthday(other.getBirthday());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      Employee parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Employee) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {

      id_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {

      id_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>string visa = 2;</code>
     */
    public String getVisa() {
      Object ref = visa_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        visa_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string visa = 2;</code>
     */
    public Builder setVisa(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      visa_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string visa = 2;</code>
     */
    public com.google.protobuf.ByteString
    getVisaBytes() {
      Object ref = visa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        visa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string visa = 2;</code>
     */
    public Builder setVisaBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      visa_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string visa = 2;</code>
     */
    public Builder clearVisa() {

      visa_ = getDefaultInstance().getVisa();
      onChanged();
      return this;
    }

    /**
     * <code>string first_name = 3;</code>
     */
    public String getFirstName() {
      Object ref = firstName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string first_name = 3;</code>
     */
    public Builder setFirstName(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      firstName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string first_name = 3;</code>
     */
    public com.google.protobuf.ByteString
    getFirstNameBytes() {
      Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string first_name = 3;</code>
     */
    public Builder setFirstNameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      firstName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string first_name = 3;</code>
     */
    public Builder clearFirstName() {

      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }

    /**
     * <code>string last_name = 4;</code>
     */
    public String getLastName() {
      Object ref = lastName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string last_name = 4;</code>
     */
    public Builder setLastName(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      lastName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string last_name = 4;</code>
     */
    public com.google.protobuf.ByteString
    getLastNameBytes() {
      Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string last_name = 4;</code>
     */
    public Builder setLastNameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      lastName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string last_name = 4;</code>
     */
    public Builder clearLastName() {

      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }

    /**
     * <code>int64 birthday = 5;</code>
     */
    public long getBirthday() {
      return birthday_;
    }

    /**
     * <code>int64 birthday = 5;</code>
     */
    public Builder setBirthday(long value) {

      birthday_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int64 birthday = 5;</code>
     */
    public Builder clearBirthday() {

      birthday_ = 0L;
      onChanged();
      return this;
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bht.pim.proto.employee.Employee)
  }

}

