// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupInfo.proto

package com.bht.pim.proto.groups;

import com.bht.pim.proto.projects.Project;
import com.bht.pim.proto.projects.ProjectOrBuilder;

/**
 * Protobuf type {@code com.bht.pim.proto.groups.GroupInfo}
 */
public final class GroupInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bht.pim.proto.groups.GroupInfo)
        GroupInfoOrBuilder {
    public static final int GROUP_FIELD_NUMBER = 1;
    public static final int ENROLLEDPROJECTS_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.bht.pim.proto.groups.GroupInfo)
    private static final GroupInfo DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<GroupInfo>
            PARSER = new com.google.protobuf.AbstractParser<GroupInfo>() {
        public GroupInfo parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new GroupInfo(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new GroupInfo();
    }

    private int bitField0_;
    private Group group_;
    private java.util.List<Project> enrolledProjects_;
    private byte memoizedIsInitialized = -1;

    // Use GroupInfo.newBuilder() to construct.
    private GroupInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private GroupInfo() {
        enrolledProjects_ = java.util.Collections.emptyList();
    }

    private GroupInfo(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        Group.Builder subBuilder = null;
                        if (group_ != null) {
                            subBuilder = group_.toBuilder();
                        }
                        group_ = input.readMessage(Group.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(group_);
                            group_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 18: {
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            enrolledProjects_ = new java.util.ArrayList<Project>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        enrolledProjects_.add(
                                input.readMessage(Project.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                enrolledProjects_ = java.util.Collections.unmodifiableList(enrolledProjects_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return GroupInfoOuterClass.internal_static_com_bht_pim_proto_groups_GroupInfo_descriptor;
    }

    public static GroupInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GroupInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GroupInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GroupInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GroupInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GroupInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GroupInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GroupInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static GroupInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static GroupInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static GroupInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GroupInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(GroupInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static GroupInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<GroupInfo> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return GroupInfoOuterClass.internal_static_com_bht_pim_proto_groups_GroupInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        GroupInfo.class, GroupInfo.Builder.class);
    }

    /**
     * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
     */
    public boolean hasGroup() {
        return group_ != null;
    }

    /**
     * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
     */
    public Group getGroup() {
        return group_ == null ? Group.getDefaultInstance() : group_;
    }

    /**
     * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
     */
    public GroupOrBuilder getGroupOrBuilder() {
        return getGroup();
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
     */
    public java.util.List<Project> getEnrolledProjectsList() {
        return enrolledProjects_;
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
     */
    public java.util.List<? extends ProjectOrBuilder>
    getEnrolledProjectsOrBuilderList() {
        return enrolledProjects_;
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
     */
    public int getEnrolledProjectsCount() {
        return enrolledProjects_.size();
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
     */
    public Project getEnrolledProjects(int index) {
        return enrolledProjects_.get(index);
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
     */
    public ProjectOrBuilder getEnrolledProjectsOrBuilder(
            int index) {
        return enrolledProjects_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (group_ != null) {
            output.writeMessage(1, getGroup());
        }
        for (int i = 0; i < enrolledProjects_.size(); i++) {
            output.writeMessage(2, enrolledProjects_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (group_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getGroup());
        }
        for (int i = 0; i < enrolledProjects_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, enrolledProjects_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof GroupInfo)) {
            return super.equals(obj);
        }
        GroupInfo other = (GroupInfo) obj;

        boolean result = true;
        result = result && (hasGroup() == other.hasGroup());
        if (hasGroup()) {
            result = result && getGroup()
                    .equals(other.getGroup());
        }
        result = result && getEnrolledProjectsList()
                .equals(other.getEnrolledProjectsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasGroup()) {
            hash = (37 * hash) + GROUP_FIELD_NUMBER;
            hash = (53 * hash) + getGroup().hashCode();
        }
        if (getEnrolledProjectsCount() > 0) {
            hash = (37 * hash) + ENROLLEDPROJECTS_FIELD_NUMBER;
            hash = (53 * hash) + getEnrolledProjectsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<GroupInfo> getParserForType() {
        return PARSER;
    }

    public GroupInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.bht.pim.proto.groups.GroupInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.bht.pim.proto.groups.GroupInfo)
            GroupInfoOrBuilder {
        private int bitField0_;
        private Group group_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                Group, Group.Builder, GroupOrBuilder> groupBuilder_;
        private java.util.List<Project> enrolledProjects_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
                Project, Project.Builder, ProjectOrBuilder> enrolledProjectsBuilder_;

        // Construct using com.bht.pim.proto.groups.GroupInfo.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return GroupInfoOuterClass.internal_static_com_bht_pim_proto_groups_GroupInfo_descriptor;
        }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return GroupInfoOuterClass.internal_static_com_bht_pim_proto_groups_GroupInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        GroupInfo.class, GroupInfo.Builder.class);
    }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getEnrolledProjectsFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (groupBuilder_ == null) {
                group_ = null;
            } else {
                group_ = null;
                groupBuilder_ = null;
            }
            if (enrolledProjectsBuilder_ == null) {
                enrolledProjects_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
            } else {
                enrolledProjectsBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return GroupInfoOuterClass.internal_static_com_bht_pim_proto_groups_GroupInfo_descriptor;
        }

        public GroupInfo getDefaultInstanceForType() {
            return GroupInfo.getDefaultInstance();
        }

        public GroupInfo build() {
            GroupInfo result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public GroupInfo buildPartial() {
            GroupInfo result = new GroupInfo(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (groupBuilder_ == null) {
                result.group_ = group_;
            } else {
                result.group_ = groupBuilder_.build();
            }
            if (enrolledProjectsBuilder_ == null) {
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    enrolledProjects_ = java.util.Collections.unmodifiableList(enrolledProjects_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.enrolledProjects_ = enrolledProjects_;
            } else {
                result.enrolledProjects_ = enrolledProjectsBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof GroupInfo) {
                return mergeFrom((GroupInfo) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(GroupInfo other) {
            if (other == GroupInfo.getDefaultInstance()) return this;
            if (other.hasGroup()) {
                mergeGroup(other.getGroup());
            }
            if (enrolledProjectsBuilder_ == null) {
                if (!other.enrolledProjects_.isEmpty()) {
                    if (enrolledProjects_.isEmpty()) {
                        enrolledProjects_ = other.enrolledProjects_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureEnrolledProjectsIsMutable();
                        enrolledProjects_.addAll(other.enrolledProjects_);
                    }
                    onChanged();
                }
            } else {
                if (!other.enrolledProjects_.isEmpty()) {
                    if (enrolledProjectsBuilder_.isEmpty()) {
                        enrolledProjectsBuilder_.dispose();
                        enrolledProjectsBuilder_ = null;
                        enrolledProjects_ = other.enrolledProjects_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        enrolledProjectsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getEnrolledProjectsFieldBuilder() : null;
                    } else {
                        enrolledProjectsBuilder_.addAllMessages(other.enrolledProjects_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            GroupInfo parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (GroupInfo) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public boolean hasGroup() {
            return groupBuilder_ != null || group_ != null;
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public Group getGroup() {
            if (groupBuilder_ == null) {
                return group_ == null ? Group.getDefaultInstance() : group_;
            } else {
                return groupBuilder_.getMessage();
            }
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public Builder setGroup(Group value) {
            if (groupBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                group_ = value;
                onChanged();
            } else {
                groupBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public Builder setGroup(
                Group.Builder builderForValue) {
            if (groupBuilder_ == null) {
                group_ = builderForValue.build();
                onChanged();
            } else {
                groupBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public Builder mergeGroup(Group value) {
            if (groupBuilder_ == null) {
                if (group_ != null) {
                    group_ =
                            Group.newBuilder(group_).mergeFrom(value).buildPartial();
                } else {
                    group_ = value;
                }
                onChanged();
            } else {
                groupBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public Builder clearGroup() {
            if (groupBuilder_ == null) {
                group_ = null;
                onChanged();
            } else {
                group_ = null;
                groupBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public Group.Builder getGroupBuilder() {

            onChanged();
            return getGroupFieldBuilder().getBuilder();
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        public GroupOrBuilder getGroupOrBuilder() {
            if (groupBuilder_ != null) {
                return groupBuilder_.getMessageOrBuilder();
            } else {
                return group_ == null ?
                        Group.getDefaultInstance() : group_;
            }
        }

        /**
         * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Group, Group.Builder, GroupOrBuilder>
        getGroupFieldBuilder() {
            if (groupBuilder_ == null) {
                groupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Group, Group.Builder, GroupOrBuilder>(
                        getGroup(),
                        getParentForChildren(),
                        isClean());
                group_ = null;
            }
            return groupBuilder_;
        }

        private void ensureEnrolledProjectsIsMutable() {
            if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                enrolledProjects_ = new java.util.ArrayList<Project>(enrolledProjects_);
                bitField0_ |= 0x00000002;
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public java.util.List<Project> getEnrolledProjectsList() {
            if (enrolledProjectsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(enrolledProjects_);
            } else {
                return enrolledProjectsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public int getEnrolledProjectsCount() {
            if (enrolledProjectsBuilder_ == null) {
                return enrolledProjects_.size();
            } else {
                return enrolledProjectsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Project getEnrolledProjects(int index) {
            if (enrolledProjectsBuilder_ == null) {
                return enrolledProjects_.get(index);
            } else {
                return enrolledProjectsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder setEnrolledProjects(
                int index, Project value) {
            if (enrolledProjectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.set(index, value);
                onChanged();
            } else {
                enrolledProjectsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder setEnrolledProjects(
                int index, Project.Builder builderForValue) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.set(index, builderForValue.build());
                onChanged();
            } else {
                enrolledProjectsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder addEnrolledProjects(Project value) {
            if (enrolledProjectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(value);
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder addEnrolledProjects(
                int index, Project value) {
            if (enrolledProjectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(index, value);
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder addEnrolledProjects(
                Project.Builder builderForValue) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(builderForValue.build());
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder addEnrolledProjects(
                int index, Project.Builder builderForValue) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.add(index, builderForValue.build());
                onChanged();
            } else {
                enrolledProjectsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder addAllEnrolledProjects(
                Iterable<? extends Project> values) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, enrolledProjects_);
                onChanged();
            } else {
                enrolledProjectsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder clearEnrolledProjects() {
            if (enrolledProjectsBuilder_ == null) {
                enrolledProjects_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                enrolledProjectsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Builder removeEnrolledProjects(int index) {
            if (enrolledProjectsBuilder_ == null) {
                ensureEnrolledProjectsIsMutable();
                enrolledProjects_.remove(index);
                onChanged();
            } else {
                enrolledProjectsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Project.Builder getEnrolledProjectsBuilder(
                int index) {
            return getEnrolledProjectsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public ProjectOrBuilder getEnrolledProjectsOrBuilder(
                int index) {
            if (enrolledProjectsBuilder_ == null) {
                return enrolledProjects_.get(index);
            } else {
                return enrolledProjectsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public java.util.List<? extends ProjectOrBuilder>
        getEnrolledProjectsOrBuilderList() {
            if (enrolledProjectsBuilder_ != null) {
                return enrolledProjectsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(enrolledProjects_);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Project.Builder addEnrolledProjectsBuilder() {
            return getEnrolledProjectsFieldBuilder().addBuilder(
                    Project.getDefaultInstance());
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public Project.Builder addEnrolledProjectsBuilder(
                int index) {
            return getEnrolledProjectsFieldBuilder().addBuilder(
                    index, Project.getDefaultInstance());
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project enrolledProjects = 2;</code>
         */
        public java.util.List<Project.Builder>
        getEnrolledProjectsBuilderList() {
            return getEnrolledProjectsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                Project, Project.Builder, ProjectOrBuilder>
        getEnrolledProjectsFieldBuilder() {
            if (enrolledProjectsBuilder_ == null) {
                enrolledProjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        Project, Project.Builder, ProjectOrBuilder>(
                        enrolledProjects_,
                        ((bitField0_ & 0x00000002) == 0x00000002),
                        getParentForChildren(),
                        isClean());
                enrolledProjects_ = null;
            }
            return enrolledProjectsBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bht.pim.proto.groups.GroupInfo)
  }

}

