// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupInfo.proto

package com.bht.pim.proto.groups;

import com.bht.pim.proto.projects.Project;
import com.bht.pim.proto.projects.ProjectOrBuilder;

public interface GroupInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.groups.GroupInfo)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
     */
    boolean hasGroup();

    /**
     * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
     */
    Group getGroup();

    /**
     * <code>.com.bht.pim.proto.groups.Group group = 1;</code>
     */
    GroupOrBuilder getGroupOrBuilder();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    java.util.List<Project>
    getEnrolledProjectList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    Project getEnrolledProject(int index);

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    int getEnrolledProjectCount();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    java.util.List<? extends ProjectOrBuilder>
    getEnrolledProjectOrBuilderList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project enrolledProject = 2;</code>
     */
    ProjectOrBuilder getEnrolledProjectOrBuilder(
            int index);
}
