// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupList.proto

package com.bht.pim.proto.groups;

public interface GroupListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.groups.GroupList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.bht.pim.proto.groups.Group group = 1;</code>
     */
    java.util.List<Group>
    getGroupList();

    /**
     * <code>repeated .com.bht.pim.proto.groups.Group group = 1;</code>
     */
    Group getGroup(int index);

    /**
     * <code>repeated .com.bht.pim.proto.groups.Group group = 1;</code>
     */
    int getGroupCount();

    /**
     * <code>repeated .com.bht.pim.proto.groups.Group group = 1;</code>
     */
    java.util.List<? extends GroupOrBuilder>
    getGroupOrBuilderList();

    /**
     * <code>repeated .com.bht.pim.proto.groups.Group group = 1;</code>
     */
    GroupOrBuilder getGroupOrBuilder(
            int index);
}
