// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectList.proto

package com.bht.pim.proto.projects;

/**
 * Protobuf type {@code com.bht.pim.proto.projects.ProjectList}
 */
public final class ProjectList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bht.pim.proto.projects.ProjectList)
        ProjectListOrBuilder {
    public static final int PROJECTS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.bht.pim.proto.projects.ProjectList)
    private static final ProjectList DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<ProjectList>
            PARSER = new com.google.protobuf.AbstractParser<ProjectList>() {
        public ProjectList parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ProjectList(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new ProjectList();
    }

    private java.util.List<Project> projects_;
    private byte memoizedIsInitialized = -1;

    // Use ProjectList.newBuilder() to construct.
    private ProjectList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ProjectList() {
        projects_ = java.util.Collections.emptyList();
    }

    private ProjectList(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            projects_ = new java.util.ArrayList<Project>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        projects_.add(
                                input.readMessage(Project.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                projects_ = java.util.Collections.unmodifiableList(projects_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return ProjectListOuterClass.internal_static_com_bht_pim_proto_projects_ProjectList_descriptor;
    }

    public static ProjectList parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ProjectList parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ProjectList parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ProjectList parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ProjectList parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ProjectList parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ProjectList parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ProjectList parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProjectList parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProjectList parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProjectList parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ProjectList parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ProjectList prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static ProjectList getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<ProjectList> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return ProjectListOuterClass.internal_static_com_bht_pim_proto_projects_ProjectList_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ProjectList.class, ProjectList.Builder.class);
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    public java.util.List<Project> getProjectsList() {
        return projects_;
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    public java.util.List<? extends ProjectOrBuilder>
    getProjectsOrBuilderList() {
        return projects_;
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    public int getProjectsCount() {
        return projects_.size();
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    public Project getProjects(int index) {
        return projects_.get(index);
    }

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    public ProjectOrBuilder getProjectsOrBuilder(
            int index) {
        return projects_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < projects_.size(); i++) {
            output.writeMessage(1, projects_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < projects_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, projects_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof ProjectList)) {
            return super.equals(obj);
        }
        ProjectList other = (ProjectList) obj;

        boolean result = true;
        result = result && getProjectsList()
                .equals(other.getProjectsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getProjectsCount() > 0) {
            hash = (37 * hash) + PROJECTS_FIELD_NUMBER;
            hash = (53 * hash) + getProjectsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<ProjectList> getParserForType() {
        return PARSER;
    }

    public ProjectList getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.bht.pim.proto.projects.ProjectList}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.bht.pim.proto.projects.ProjectList)
            ProjectListOrBuilder {
        private int bitField0_;
        private java.util.List<Project> projects_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
                Project, Project.Builder, ProjectOrBuilder> projectsBuilder_;

        // Construct using com.bht.pim.proto.projects.ProjectList.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProjectListOuterClass.internal_static_com_bht_pim_proto_projects_ProjectList_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProjectListOuterClass.internal_static_com_bht_pim_proto_projects_ProjectList_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ProjectList.class, ProjectList.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getProjectsFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (projectsBuilder_ == null) {
                projects_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                projectsBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return ProjectListOuterClass.internal_static_com_bht_pim_proto_projects_ProjectList_descriptor;
        }

        public ProjectList getDefaultInstanceForType() {
            return ProjectList.getDefaultInstance();
        }

        public ProjectList build() {
            ProjectList result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public ProjectList buildPartial() {
            ProjectList result = new ProjectList(this);
            int from_bitField0_ = bitField0_;
            if (projectsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    projects_ = java.util.Collections.unmodifiableList(projects_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.projects_ = projects_;
            } else {
                result.projects_ = projectsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof ProjectList) {
                return mergeFrom((ProjectList) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(ProjectList other) {
            if (other == ProjectList.getDefaultInstance()) return this;
            if (projectsBuilder_ == null) {
                if (!other.projects_.isEmpty()) {
                    if (projects_.isEmpty()) {
                        projects_ = other.projects_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureProjectsIsMutable();
                        projects_.addAll(other.projects_);
                    }
                    onChanged();
                }
            } else {
                if (!other.projects_.isEmpty()) {
                    if (projectsBuilder_.isEmpty()) {
                        projectsBuilder_.dispose();
                        projectsBuilder_ = null;
                        projects_ = other.projects_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        projectsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getProjectsFieldBuilder() : null;
                    } else {
                        projectsBuilder_.addAllMessages(other.projects_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            ProjectList parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (ProjectList) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureProjectsIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                projects_ = new java.util.ArrayList<Project>(projects_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public java.util.List<Project> getProjectsList() {
            if (projectsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(projects_);
            } else {
                return projectsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public int getProjectsCount() {
            if (projectsBuilder_ == null) {
                return projects_.size();
            } else {
                return projectsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Project getProjects(int index) {
            if (projectsBuilder_ == null) {
                return projects_.get(index);
            } else {
                return projectsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder setProjects(
                int index, Project value) {
            if (projectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureProjectsIsMutable();
                projects_.set(index, value);
                onChanged();
            } else {
                projectsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder setProjects(
                int index, Project.Builder builderForValue) {
            if (projectsBuilder_ == null) {
                ensureProjectsIsMutable();
                projects_.set(index, builderForValue.build());
                onChanged();
            } else {
                projectsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder addProjects(Project value) {
            if (projectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureProjectsIsMutable();
                projects_.add(value);
                onChanged();
            } else {
                projectsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder addProjects(
                int index, Project value) {
            if (projectsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureProjectsIsMutable();
                projects_.add(index, value);
                onChanged();
            } else {
                projectsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder addProjects(
                Project.Builder builderForValue) {
            if (projectsBuilder_ == null) {
                ensureProjectsIsMutable();
                projects_.add(builderForValue.build());
                onChanged();
            } else {
                projectsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder addProjects(
                int index, Project.Builder builderForValue) {
            if (projectsBuilder_ == null) {
                ensureProjectsIsMutable();
                projects_.add(index, builderForValue.build());
                onChanged();
            } else {
                projectsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder addAllProjects(
                Iterable<? extends Project> values) {
            if (projectsBuilder_ == null) {
                ensureProjectsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, projects_);
                onChanged();
            } else {
                projectsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder clearProjects() {
            if (projectsBuilder_ == null) {
                projects_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                projectsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Builder removeProjects(int index) {
            if (projectsBuilder_ == null) {
                ensureProjectsIsMutable();
                projects_.remove(index);
                onChanged();
            } else {
                projectsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Project.Builder getProjectsBuilder(
                int index) {
            return getProjectsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public ProjectOrBuilder getProjectsOrBuilder(
                int index) {
            if (projectsBuilder_ == null) {
                return projects_.get(index);
            } else {
                return projectsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public java.util.List<? extends ProjectOrBuilder>
        getProjectsOrBuilderList() {
            if (projectsBuilder_ != null) {
                return projectsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(projects_);
            }
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Project.Builder addProjectsBuilder() {
            return getProjectsFieldBuilder().addBuilder(
                    Project.getDefaultInstance());
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public Project.Builder addProjectsBuilder(
                int index) {
            return getProjectsFieldBuilder().addBuilder(
                    index, Project.getDefaultInstance());
        }

        /**
         * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
         */
        public java.util.List<Project.Builder>
        getProjectsBuilderList() {
            return getProjectsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                Project, Project.Builder, ProjectOrBuilder>
        getProjectsFieldBuilder() {
            if (projectsBuilder_ == null) {
                projectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        Project, Project.Builder, ProjectOrBuilder>(
                        projects_,
                        ((bitField0_ & 0x00000001) == 0x00000001),
                        getParentForChildren(),
                        isClean());
                projects_ = null;
            }
            return projectsBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.bht.pim.proto.projects.ProjectList)
  }

}

