// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectNumbers.proto

package com.bht.pim.proto.projects;

public interface ProjectNumbersOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.projects.ProjectNumbers)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 projectNumber = 1;</code>
     */
    java.util.List<Long> getProjectNumberList();

    /**
     * <code>repeated int64 projectNumber = 1;</code>
     */
    int getProjectNumberCount();

    /**
     * <code>repeated int64 projectNumber = 1;</code>
     */
    long getProjectNumber(int index);
}
