// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package com.bht.pim.proto.projects;

public interface ProjectListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.projects.ProjectList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    java.util.List<Project>
    getProjectsList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    Project getProjects(int index);

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    int getProjectsCount();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    java.util.List<? extends ProjectOrBuilder>
    getProjectsOrBuilderList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.Project projects = 1;</code>
     */
    ProjectOrBuilder getProjectsOrBuilder(
            int index);
}
