// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package com.bht.pim.proto.projects;

public interface ProjectGroupsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.projects.ProjectGroups)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.bht.pim.proto.projects.ProjectGroup projectGroups = 1;</code>
     */
    java.util.List<ProjectGroup>
    getProjectGroupsList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.ProjectGroup projectGroups = 1;</code>
     */
    ProjectGroup getProjectGroups(int index);

    /**
     * <code>repeated .com.bht.pim.proto.projects.ProjectGroup projectGroups = 1;</code>
     */
    int getProjectGroupsCount();

    /**
     * <code>repeated .com.bht.pim.proto.projects.ProjectGroup projectGroups = 1;</code>
     */
    java.util.List<? extends ProjectGroupOrBuilder>
    getProjectGroupsOrBuilderList();

    /**
     * <code>repeated .com.bht.pim.proto.projects.ProjectGroup projectGroups = 1;</code>
     */
    ProjectGroupOrBuilder getProjectGroupsOrBuilder(
            int index);
}
