// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupInfo.proto

package com.bht.pim.proto.group;

public interface GroupIdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bht.pim.proto.group.GroupId)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();
}
